version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
  moviedb:
    image: mcr.microsoft.com/mssql/server:2019-latest